$ENV:TEST_DUFFLE_ACI_DRIVER_SUBSCRIPTION_ID=""
$ENV:TEST_DUFFLE_ACI_DRIVER_TENANT_ID=""
$ENV:TEST_DUFFLE_ACI_DRIVER_CLIENT_ID=""
$ENV:TEST_DUFFLE_ACI_DRIVER_CLIENT_SECRET=""
$ENV:TEST_DUFFLE_ACI_DRIVER_LOCATION=""
$ENV:TEST_DUFFLE_ACI_DRIVER_STATE_FILESHARE=""

$ENV:TEST_DUFFLE_ACI_DRIVER_STATE_STORAGE_ACCOUNT_NAME=""
$ENV:TEST_DUFFLE_ACI_DRIVER_STATE_STORAGE_ACCOUNT_KEY=""
go test -v -timeout 1h ./pkg/azure, ./pkg/driver -args -runazuretest -verbosedriveroutput
