#!/bin/bash
export TEST_DUFFLE_ACI_DRIVER_SUBSCRIPTION_ID=
export TEST_DUFFLE_ACI_DRIVER_TENANT_ID=
export TEST_DUFFLE_ACI_DRIVER_CLIENT_ID=
export TEST_DUFFLE_ACI_DRIVER_CLIENT_SECRET=
export TEST_DUFFLE_ACI_DRIVER_LOCATION=
export TEST_DUFFLE_ACI_DRIVER_STATE_FILESHARE=
export TEST_DUFFLE_ACI_DRIVER_STATE_STORAGE_ACCOUNT_NAME=
export TEST_DUFFLE_ACI_DRIVER_STATE_STORAGE_ACCOUNT_KEY=
go test -v -timeout 1h ./pkg/azure, ./pkg/driver -args -runazuretest -verbosedriveroutput