$ENV:TEST_CNAB_AZURE_SUBSCRIPTION_ID=""
$ENV:TEST_CNAB_AZURE_TENANT_ID=""
$ENV:TEST_CNAB_AZURE_CLIENT_ID=""
$ENV:TEST_CNAB_AZURE_CLIENT_SECRET=""
$ENV:TEST_CNAB_AZURE_LOCATION=""
$ENV:TEST_CNAB_AZURE_STATE_FILESHARE=""
$ENV:TEST_CNAB_AZURE_STATE_STORAGE_ACCOUNT_NAME=""
$ENV:TEST_CNAB_AZURE_STATE_STORAGE_ACCOUNT_KEY=""
$ENV:TEST_CNAB_AZURE_RUN_CLI_LOGIN_TEST=false
$ENV:GO111MODULE='on'
go test -v -timeout 1h ./pkg/... -args -runazuretest -verbosedriveroutput