#!/bin/sh

set -e

action=$CNAB_ACTION
name=$CNAB_INSTALLATION_NAME
param=${CNAB_P_HELLO:-hello}
login_type="${DUFFLE_ACI_DRIVER_MSI_TYPE:-none}"

echo "$(date) $param world"
case $action in
    install)
    echo "$(date) Install action"
    i=0
    while [ $i -lt 3 ]
    do 
        echo "$(date) STDOUT:Running..."
        (>&2 echo "$(date) STDERR:Running...")
        sleep 5
        i=$((i+1))
    done
    
    if [[ "${login_type}" == "user" ]]; then
        az login --identity -u "${DUFFLE_ACI_DRIVER_USER_MSI_RESOURCE_ID}"
        az group list
    fi

    if [[ "${login_type}" == "system" ]]; then
        az login --identity
        az group list
    fi
    ;;
    uninstall)
    echo "uninstall action"
    ;;
    upgrade)
    echo "Upgrade action"
    ;;
    downgrade)
    echo "Downgrade action"
    ;;
    status)
    echo "Status action"
    ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "$(date) Action $action complete for $name"