#!/bin/bash

set -e

action=$CNAB_ACTION
name=$CNAB_INSTALLATION_NAME

case $action in
    install)
    echo "$(date) Install action"
    echo ${INPUT_1} > "${STATE_PATH}/output"
    ;;
    uninstall)
    echo "uninstall action"
    ;;
    upgrade)
    echo "Upgrade action"
    ;;
    echo "No action for $action"
    ;;
esac
echo "$(date) Action $action complete for $name"