#!/bin/bash

set -e

action=$CNAB_ACTION
name=$CNAB_INSTALLATION_NAME

case $action in
    install)
    echo "$(date) Install action"
    echo "${STATE_PATH}/teststate"
    ls -al "${STATE_PATH}"
    echo -n "TEST" > "${STATE_PATH}/teststate"
    ls -al "${STATE_PATH}/teststate"
    cat "${STATE_PATH}/teststate"
    ;;
    uninstall)
    echo "uninstall action"
    ;;
    upgrade)
    echo "Upgrade action"
    ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "$(date) Action $action complete for $name"